### ISSUE TITLE
ReferenceError: CSS is not defined  in Next JS Build 

### ISSUE THREAD

**Issue by jothachil** [grubersjoe/react-github-calendar#121]
```
▲ Next.js 14.2.15
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
 ✓ Checking validity of types    
 ✓ Collecting page data    
   Generating static pages (11/38)  [==  ]ReferenceError: CSS is not defined
    at validateInput (.....node_modules/.pnpm/react-activity-calendar@2.6.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-activity-calendar/build/index.js:317:7)
    at createTheme (.....node_modules/.pnpm/react-activity-calendar@2.6.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-activity-calendar/build/index.js:289:5)
    at .....node_modules/.pnpm/react-activity-calendar@2.6.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-activity-calendar/build/index.js:371:17
    at Wc (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
    at Z (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:476)
    at Z (.....node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

Error occurred prerendering page "/about". Read more: https://nextjs.org/docs/messages/prerender-error

```

Getting this error when I add theme prop. Works during nextjs dev, But while doing build getting this message.

Versions
```
"react-github-calendar": "^4.4.1",
"react": "^18.3.1",
"react-dom": "^18.3.1",
```

**Comment by grubersjoe** [comment]
Thanks for reporting this. I've prepared a PR.

**Comment by jothachil** [comment]
This working now thanks 😇
