### ISSUE TITLE
Error Fetching Profile Stats

### ISSUE THREAD

**Issue by actuallyakshat** [grubersjoe/react-github-calendar#144]
the GitHubCalendar component stopped working for me in my project and I got an error message saying: 
Error – Fetching GitHub contribution data for "actuallyakshat" failed." Upon checking the demo website, I faced the same issue.

![image](https://github.com/user-attachments/assets/3ce09d67-1b08-48ba-8af7-9df8f6eac0e6)

**Comment by grubersjoe** [comment]
Hey. Thanks for reporting this. Probably something has changed on GitHub's side and then the scraping API breaks. I'll look into this later.

**Comment by grubersjoe** [comment]
Hi. So I checked, there must have been some issue on GitHub's end because the API logs show scraping errors, but everything seems fine again.

**Comment by actuallyakshat** [comment]
Hey.
I am still facing the same issue. What is the work around for this?

**Comment by grubersjoe** [comment]
This does work, though, doesn't it?
https://grubersjoe.github.io/react-github-calendar/#/?user=actuallyakshat

What is the issue you face exactly?

**Comment by bhargavi35** [comment]
I'm also facing an issue with GitHub-calendar while using it, 
shows an err like this, can anyone plz help me out 

ERROR
dateFns.eachDayOfInterval is not a function
TypeError: dateFns.eachDayOfInterval is not a function
    at generateEmptyData (http://localhost:3000/static/js/bundle.js:9924:24)
    at http://localhost:3000/static/js/bundle.js:10188:18
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:23845:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:27094:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:29155:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:14101:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:14145:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:14202:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:34100:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33348:16)

**Comment by grubersjoe** [comment]
@bhargavi35 

Please get into the habit to search for issues in the existing ones first: https://github.com/grubersjoe/react-github-calendar/issues/137, https://github.com/grubersjoe/react-github-calendar/issues/151. Several issues have been created about this error already.

I suppose you're using Create React App? CRA is unsupported as explained in the [README](https://github.com/grubersjoe/react-github-calendar?tab=readme-ov-file#why-is-create-react-app-unsupported). [Vite](https://vite.dev/) is a nice replacement that works very well.
