### ISSUE TITLE
dateFns.eachDayOfInterval is not a function

### ISSUE THREAD

**Issue by oscody** [grubersjoe/react-github-calendar#151]
`
import React from "react";
import GitHubCalendar from "react-github-calendar";

function Github() {
  return (
    <>
      <GitHubCalendar
        username="oscody"
      />
    </>
  );
}

export default Github;

`

    "react-github-calendar": "^4.5.2",
    "react": "^18.3.1",

`Uncaught runtime errors:
×
ERROR
dateFns.eachDayOfInterval is not a function
TypeError: dateFns.eachDayOfInterval is not a function
    at generateEmptyData (http://localhost:3000/static/js/bundle.js:12474:24)
    at http://localhost:3000/static/js/bundle.js:12738:18
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:26395:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:29644:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:31705:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:16651:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:16695:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:16752:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:36650:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:35898:16)
ERROR
dateFns.eachDayOfInterval is not a function
TypeError: dateFns.eachDayOfInterval is not a function
    at generateEmptyData (http://localhost:3000/static/js/bundle.js:12474:24)
    at http://localhost:3000/static/js/bundle.js:12738:18
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:26395:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:29644:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:31705:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:16651:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:16695:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:16752:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:36650:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:35898:16)
ERROR
dateFns.eachDayOfInterval is not a function
TypeError: dateFns.eachDayOfInterval is not a function
    at generateEmptyData (http://localhost:3000/static/js/bundle.js:12474:24)
    at http://localhost:3000/static/js/bundle.js:12738:18
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:26395:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:29644:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:31705:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:36628:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:35898:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:35821:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:35794:11)
    at recoverFromConcurrentError (http://localhost:3000/static/js/bundle.js:35286:24). `

**Comment by grubersjoe** [comment]
Please get into the habit to search for an issue in the existing ones first: https://github.com/grubersjoe/react-github-calendar/issues/137

I suppose you're using Create React App? CRA is unsupported as explained in the [README](https://github.com/grubersjoe/react-github-calendar?tab=readme-ov-file#why-is-create-react-app-unsupported).

**Comment by oscody** [comment]
> Please get into the habit to search for issues in the existing ones first: #137
> 
> I suppose you're using Create React App? CRA is unsupported as explained in the [README](https://github.com/grubersjoe/react-github-calendar?tab=readme-ov-file#why-is-create-react-app-unsupported).

Thank lesson learned i move my project to vite resolved the issue thank you
